### ISSUE TITLE
Free web scraping tool for your dashboard

### ISSUE THREAD

**Issue by vickyRathee** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#10]
Hey @OssamaRafique If you are using a paid scraping tool. You can switch to [Agenty](https://www.agenty.com/), we've free public datasets for COVID-19 web scraping

https://www.agenty.com/docs/how-to/how-to-scrape-covid-19-data-from-websites

**Comment by OssamaRafique** [comment]
Hi, No I Im using free one.
