### ISSUE TITLE
Invalid host header

### ISSUE THREAD

**Issue by ethcar** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#11]
Able to run the Application on the loaclhost and works fine.
Deployed on Digital ocean with apache configuration tested other apps work fine with Domain name and HTTPS.

Running this project results in error " Invalid host header "

tried all possible resolutions, updated the server hostname to match the same site(project)

Can tell me how I can fix this last issue of invalid host headers

**Comment by OssamaRafique** [comment]
Can you please share the screenshot? Also, I've updated the server.js file please check that too.

**Comment by ethcar** [comment]
![image](https://user-images.githubusercontent.com/39594689/77823852-421a4280-7124-11ea-8d70-52f9952c1cbd.png)

![image](https://user-images.githubusercontent.com/39594689/77823860-50685e80-7124-11ea-9036-a2cf44a3ef81.png)

Compile is successful, Updated the server.js file as pointed out, still the same issue.

Also referred to : https://github.com/angular/angular-cli/issues/6349

Where have you hosted your site, I am running on Digital Ocean?

**Comment by OssamaRafique** [comment]
Why you're starting it like that?
Please build and deploy static files.

Run this command
`ng build --prod`
Upload the files in your dist folder to the server.

**Comment by OssamaRafique** [comment]
If you still have issue, Please reopen this issue.
Thanks.
