### ISSUE TITLE
Might be your data is bit behind

### ISSUE THREAD

**Issue by techiesalman** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#12]
In India nowadays we are seeing data from this URL https://www.covid19india.org/. It seems like their data is quite accurate. Can you also please look into this and use their API to bring data accurately.

Thank You.

**Comment by OssamaRafique** [comment]
Hi, Its correct I think, our data is updated frequently.

**Comment by OssamaRafique** [comment]
If you still think there's in issue please reopen so I can resolve.
