### ISSUE TITLE
Data not updating

### ISSUE THREAD

**Issue by urosmlade** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#15]
Hi.
I really love your website. It is really well made and easy to use.
Just one thing,
I saw that numbers are not updating today for countries. Are you working on something or is it bug that needs to be fixed?

**Comment by OssamaRafique** [comment]
Hi,
Thank you!
I fixed it. Please check it.

**Comment by urosmlade** [comment]
It is working now. 
Thank you.
