### ISSUE TITLE
Weblate translation platform

### ISSUE THREAD

**Issue by comradekingu** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#17]
Hello, I know a lot of people who want to contribute translations.
Maybe the HTML-files could be converted to one of the supported formats
https://docs.weblate.org/en/latest/formats.html
and then added for hosting here https://weblate.org/hosting/ ? :)

**Comment by MadTed** [comment]
Hi there,
I would like to suggest a multi-language support, no big thing.
Just let's add a county-selection for already done translations, 
a config with country code,
and translate all html-files.
I would like to contribute a german translation.

**Comment by OssamaRafique** [comment]
Sorry, I missed this issue. I will add languages file tomorrow :)

**Comment by MadTed** [comment]
cool, so I can start with german ...
:)

**Comment by OssamaRafique** [comment]
Im really sorry for the delay but I added the translations in my latest commit:
Please Check it out: 
https://github.com/OssamaRafique/Covid-19-Statistics-Dashboard-Angular-9/commit/dbbc24765127224ea44c29b5cd5191b0d994404b

To Add more translations, Please clone the en.json translation file in assets/i18n with language code name e.g(de.json) and replace the text inside it with your own.

After that goto app.component.ts and add your language code in there e.g 
```
export class AppComponent {
  constructor(public translate: TranslateService) {
    translate.addLangs(['en','fr','de']); //Add here
      translate.setDefaultLang('en');
      const browserLang = translate.getBrowserLang();
      translate.use(browserLang.match(/en|de|fr/) ? browserLang : 'en'); //and here
  }
}
```

Thank you
