### ISSUE TITLE
Name of Repository

### ISSUE THREAD

**Issue by MadTed** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#18]
For me this is no tracking app, the term is confusing, I guess.
In fact, many apps call them "tracker" ...

I would like to suggest to only name it Corona-Dashboad-Angular-9.
On the other hand there are many corona viruses out there.
Perhaps a name like Covid-19-Dashboard-Angular-9 is better?!?
What do you think?
Greets

**Comment by MadTed** [comment]
I've started to develop a real tracking app.
take a look at
https://github.com/MadTed/PD-Tracking-App-hackthepandemic

**Comment by OssamaRafique** [comment]
Yes that's better. I renamed the repo.
Thanks for suggestion.
