### ISSUE TITLE
Merges and Failed Deploys

### ISSUE THREAD

**Issue by yavuzoktay** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#23]
Hello, you are doing merge but it has no effect, can you get new deploy?
https://coronastatistics.live/

**Comment by zer0kool** [comment]
You can also deploy this on now.sh its better than heroku, heroku servers are very slow.

**Comment by OssamaRafique** [comment]
Sorry I got too busy that I couldn't manage this project.
