### ISSUE TITLE
Anything You want done with this?

### ISSUE THREAD

**Issue by srz2** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#3]
This isn't an issue, just a question. I dont know a "better" way to contact?

I might be interested in helping with this project, I dont know angular but might be willing to learn. Do you have anything you are wanting to see in this project?

**Comment by OssamaRafique** [comment]
I'm very happy to see that you are interested in working on this project.
There're few things I want to be done:
-Newsletter (users will get the details in their email)
-Compare countries
-State Map and Their data (e.g all states of USA, or china etc.)

**Comment by srz2** [comment]
I think I want to try to do states if that’s ok. If I’m not quick enough and you want to implement it, that’s ok, but I can try this first

**Comment by OssamaRafique** [comment]
Sure, I will make the endpoint to get the state's data that you can use in the app.
