### ISSUE TITLE
Server Configuration 

### ISSUE THREAD

**Issue by alexcash09** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#4]
Currently there is no default configuration in the server project to configure where the data is coming from. There is an example configuration but it's not really intuitive on what a developer would need to add to that to get the backend working. Details in the README or comments in the code should be added so that the server can be configured correctly

**Comment by sagar-18** [comment]
> Currently there is no default configuration in the server project to configure where the data is coming from. There is an example configuration but it's not really intuitive on what a developer would need to add to that to get the backend working. Details in the README or comments in the code should be added so that the server can be configured correctly

Deploy it on zeit.co

**Comment by OssamaRafique** [comment]
Please check now.
