### ISSUE TITLE
Unable to Install On ubuntu server

### ISSUE THREAD

**Issue by ethcar** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#5]
Errors :  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo EAI_AGAIN host host:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)

Have installed and configured Redis server. Please also give the steps to setup the domain or,
It would be very nice, if you can convert this in Docker image. And steps on how to setup the Domain name.

Thank you

**Comment by OssamaRafique** [comment]
Hi, may I know the Redis version you're using and the hosting company? So I can reproduce this error at my end.
Thanks.

**Comment by OssamaRafique** [comment]
Also as a suggestion, you can get a Redis cloud instance with 30MB storage from Heroku for free. And that is more than enough for this project.

**Comment by OssamaRafique** [comment]
Please check this guide it will help you. If not you can always reopen the issue. Thanks.
https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-18-04

**Comment by ethcar** [comment]
I am working with digital ocean, and have installed REDIS as per the instruction.

Can nyou tell me what value should be there for host and pass in the config.

Maybe that's what I am doing wrong

**Comment by ethcar** [comment]
I tried this app on heroku and it failed. Can you provide steps to apply this on heroku app
