### ISSUE TITLE
trouble with parsing tables

### ISSUE THREAD

**Issue by srz2** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#7]
I am not sure how your parsing is working but I tried to tackle states on the server side and I cant get it.

However I am having issues with your parsing as well. I haven't changed anything and I'm getting errors like 

`(node:6923) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at getCountries (/Users/myusername/projects/Corona-Statistics-And-Tracker-Dashboard-Angular-9/server/server.js:94:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6923) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6923) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by OssamaRafique** [comment]
Hi, 
Thank you for letting me know. I just pushed a new update. It's fixed now.
