### ISSUE TITLE
deprecated files

### ISSUE THREAD

**Issue by cbmdk** [OssamaRafique/Corona-Statistics-And-Tracker-Dashboard-Angular-9#8]
Hey,
according to https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series it seems like the files you rely on are deprecated... just fyi :)

**Comment by OssamaRafique** [comment]
Thank you for this info. I'll update this soon.

**Comment by cbmdk** [comment]
and now the files you rely on are gone so I guess data is not updated

**Comment by OssamaRafique** [comment]
FIXED, Please check.
